### ISSUE TITLE
TypeError: array_keys()...ExternalModule.php:121

### ISSUE THREAD

**Issue by pbchase** [ctsit/prevent_past_or_future_dates#10]
This module seems to have another PHP 8 bug. The request was made on an unauthenticated browser. The `id` and `page` parameters are bogus.

```
Date: Tuesday, September 3, 2024 at 10:11 AM
Subject: REDCap External Module Hook Exception - prevent_past_or_future_dates
[This message was automatically generated by REDCap]

The 'prevent_past_or_future_dates' module threw the following exception when calling the hook method 'redcap_every_page_top':

TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www.backup/redcap-20240819T2043/modules/prevent_past_or_future_dates_v1.0.2/ExternalModule.php:121
Stack trace:
#0 /var/www.backup/redcap-20240819T2043/modules/prevent_past_or_future_dates_v1.0.2/ExternalModule.php(121): array_keys()
#1 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3156): PreventPastOrFutureDates\ExternalModule\ExternalModule->redcap_every_page_top()
#2 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3323): ExternalModules\ExternalModules::startHook()
#3 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/ExternalModules/classes/ExternalModules.php(3356): ExternalModules\ExternalModules::ExternalModules\{closure}()
#4 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook()
#5 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/HtmlPage.php(151): Hooks::call()
#6 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Config/init_functions.php(671): HtmlPage->PrintHeader()
#7 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Libraries/PEAR/Auth.php(587): loginFunction()
#8 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Libraries/PEAR/Auth.php(530): Auth->login()
#9 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/Authentication.php(1873): Auth->start()
#10 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/Authentication.php(908): Authentication::checkLogin()
#11 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/Authentication.php(459): Authentication::tableBasedLogin()
#12 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Classes/System.php(937): Authentication::authenticate()
#13 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/Config/init_project.php(7): System::initProjectPage()
#14 /var/www.backup/redcap-20240819T2043/redcap_v14.6.2/DataEntry/index.php(6): require_once('...')
#15 {main}

URL: https://XXXXXXX/redcap/redcap_v14.6.2/DataEntry/index.php?pid=9941&id=4919903926734636&event_id=95960&page=cbegvdvcbag_bae_fghel_cbegafe_dbagbdg_vaabezbgvba
Server: XXXXXXX
User: 
Project ID: 9941
Module Name: Prevent Past or Future Dates (prevent_past_or_future_dates)
Module Author(s): XXXXXXX
Run Time: 0 seconds

```

**Comment by pbchase** [comment]
Addressed by PR #13
